#!/bin/bash
if [ $# -lt 2 ]
then
	echo "Usage: runner savedir declination"
	exit
fi
DECLN=$2
SAVE=$1
usbtype=`lsusb|awk '/Bus / {print $6}'`
echo usbtype $usbtype
for usbline in $usbtype
do
	case $usbline in
		2500:00*)
			SRATE=15e6
			DEVICE="uhd,type=b200,num_recv_frames=512,otw_format=sc8,master_clock_rate=30e6"
			RFGAIN=60
			DEVNAME="USRP B2XX"
			;;
		1d50:*)
			SRATE=10e6
			DEVICE="airspy,linearity=1"
			RFGAIN=40
			DEVNAME="AirSpy R2"
			SRATE=`airspy_info |awk '/6.0.*MSPS/ {print "6.0e6"}
			/10.0.*MSPS/ {print "10.0e6"}'`
		;;
	esac
done
while true
do
    if [ -e $2 ]
    then
		DECLN=`cat $2`
	fi
	echo "Starting using a $DEVNAME device" at $SRATE SPS
	frb_hunter2.py --device "$DEVICE" --rfgain $RFGAIN --srate $SRATE --freq 1415.0e6
	for sd in 0.5 1 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0
	do
	    rm -f /run/user/$UID/frb-event.json
		frb_bulk_analyser.py --declination $2 --infile /run/user/$UID/frb_tmp.dat --srate `cat frb_rate.txt` \
		  --threshold 3.5 --sdelay $sd --prefix /run/user/$UID/
		if [ -e /run/user/$UID/frb-event.json ]
		then
			ts=`date -u +%Y%m%d-%H%M%S`
			mv /run/user/$UID/frb_tmp.dat $SAVE/$ts.bin
			mv /run/user/%UID/frb-event.josn $SAVE/%ts.json
			break
		fi
	done
	sleep 10
done
		
