#!/bin/bash
if [ $# -lt 3 ]
then
	echo "Usage: runner savedir declination longitude"
	exit
fi
TMPDIR=$HOME
DECLN=$2
SAVE=$1
LONGIT=$3
usbtype=`lsusb|awk '/Bus / {print $6}'`
echo usbtype $usbtype
for usbline in $usbtype
do
	case $usbline in
		2500:00*)
			SRATE=15e6
			FREQ=1415.0e6
			DEVICE="uhd,type=b200,num_recv_frames=512,otw_format=sc8,master_clock_rate=30e6"
			RFGAIN=70
			DEVNAME="USRP B2XX"
			;;
		1d50:*)
			SRATE=10e6
			FREQ=1418.0e6
			DEVICE="airspy,linearity=1"
			RFGAIN=40
			DEVNAME="AirSpy R2"
			SRATE=`airspy_info |awk '/6.0.*MSPS/ {print "6.0e6"}
			/10.0.*MSPS/ {print "10.0e6"}'`
		;;
	esac
done
while true
do
    #
    # If declinaton specifier is apparently a file...
    #
    if [ -e $2 ]
    then
		DECLN=`cat $2`
	fi
	echo "Starting using a $DEVNAME device" at $SRATE SPS
	#
	# Record 10 minutes worth of detector channel-bank data
	#
	# It will produce output in <prefix>/frb_tmp.dat
	# It also produces a "frb_rate.txt" file in current directory to convey the
	#  selected channel rate.  The channel-rate usually allows for 130-150usec
	#  time-domain resolution.
	#
	frb_hunter2.py --device "$DEVICE" --rfgain $RFGAIN --srate $SRATE --freq $FREQ --seconds 600 \
	  --prefix $TMPDIR/
	
	#
	# Run a whack of trial-dedispersions, looking for a pulse
	#
	for sd in 0.5 1 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0
	do
	    rm -f /run/user/$UID/frb-event.json
	    CRATE=`cat frb_rate.txt`
		frb_bulk_analyser.py --declination $DECLN --infile $TMPDIR/frb_tmp.dat --srate $CRATE \
		  --threshold 3.5 --sdelay $sd --prefix $TMPDIR/ --seconds 600 --longitude $LONGIT
		if [ -e $TMPDIR/frb-event.json ]
		then
			ts=`date -u +%Y%m%d-%H%M%S`
			count=`awk '/scount/ {print $2}' $TMPDIR/frb-event.json`
			offset=`expr $count - $CRATE`
			dd if=$TMPDIR/frb_tmp.dat of=$SAVE/$ts-$sd.bin bs=64 skip=$offset count=`expr $CRATE * 2`
			#mv $TMPDIR/frb_tmp.dat $SAVE/$ts.bin
			
			mv $TMPDIR/frb-event.josn $SAVE/$ts-$sd.json
			break
		fi
	done
	sleep 10
done

